const { chromium } = require(process.env.PLAYWRIGHT || 'playwright')
const assert = require('node:assert/strict')
const URL = process.env.URL || 'http://localhost:5173/DairyOptimizer/'

;(async () => {
  const b = await chromium.launch({ channel: 'chrome' })
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, serviceWorkers: 'block', hasTouch: true, isMobile: true })
  const p = await ctx.newPage()
  const errors = []
  p.on('pageerror', (e) => errors.push(e.message))
  p.on('console', (m) => m.type() === 'error' && errors.push(m.text()))
  const step = async (name, fn) => {
    try {
      await fn()
      console.log('ok  ', name)
    } catch (e) {
      console.log('FAIL', name, '\n    ', e.message.split('\n')[0])
    }
  }
  const doc = () => p.evaluate(() => JSON.parse(localStorage.getItem('achieve-v3') || 'null'))
  const sheets = () => p.locator('.sheet').count()

  await p.goto(URL)
  await p.locator('h1').first().waitFor()

  await step('quick add task (today)', async () => {
    await p.click('.tabbar .fab')
    await p.fill('input.big-input', 'ทดสอบงาน A')
    await p.click('button.chip:has-text("Today")')
    await p.click('button.chip.tone:has-text("Algo")')
    await p.click('.sheet button:has-text("Add task")')
    await p.waitForTimeout(500)
    assert.equal(await sheets(), 0)
    await p.locator('.task-row:has-text("ทดสอบงาน A")').waitFor()
    const d = await doc()
    const t = d.tasks.find((x) => x.title === 'ทดสอบงาน A')
    assert.ok(t && t.subjectId === 'sub-254383-2' && t.due)
  })

  await step('complete + undo', async () => {
    await p.click('.task-row:has-text("ทดสอบงาน A") .check')
    await p.waitForTimeout(300)
    assert.ok((await doc()).tasks.find((x) => x.title === 'ทดสอบงาน A').doneAt)
    await p.click('.task-row:has-text("ทดสอบงาน A") .check')
    await p.waitForTimeout(300)
    assert.equal((await doc()).tasks.find((x) => x.title === 'ทดสอบงาน A').doneAt, null)
  })

  await step('task sheet edit checklist + autosave', async () => {
    await p.click('.task-row:has-text("ทดสอบงาน A") .row-title')
    await p.locator('.sheet').waitFor()
    await p.fill('.checklist input[placeholder]', 'ขั้นแรก')
    await p.keyboard.press('Enter')
    await p.fill('.task-editor textarea[placeholder="Notes"]', 'โน้ตทดสอบ')
    await p.waitForTimeout(900)
    const t = (await doc()).tasks.find((x) => x.title === 'ทดสอบงาน A')
    assert.equal(t.checklist[0]?.title, 'ขั้นแรก')
    assert.equal(t.notes, 'โน้ตทดสอบ')
  })

  await step('android back closes sheet', async () => {
    await p.goBack()
    await p.waitForTimeout(1200)
    assert.equal(await sheets(), 0, 'sheet still open after back')
    assert.ok(p.url().includes('DairyOptimizer'))
  })

  await step('delete from sheet + undo', async () => {
    await p.click('.task-row:has-text("ทดสอบงาน A") .row-title')
    await p.click('button[aria-label="Delete task"]')
    await p.waitForTimeout(400)
    assert.ok((await doc()).tasks.find((x) => x.title === 'ทดสอบงาน A').deleted)
    await p.click('.toast .undo')
    await p.waitForTimeout(400)
    assert.ok(!(await doc()).tasks.find((x) => x.title === 'ทดสอบงาน A').deleted)
    await p.locator('.task-row:has-text("ทดสอบงาน A")').waitFor()
  })

  await step('private task with new PIN is encrypted', async () => {
    await p.click('.tabbar .fab')
    await p.fill('input.big-input', 'งานลับมาก')
    await p.click('.sheet button[role="switch"]')
    await p.click('.sheet button:has-text("Add task")')
    await p.locator('.pin-title').waitFor()
    for (const k of '135790135790') await p.click(`.pin-pad .key[aria-label="${k}"]`)
    await p.waitForTimeout(2500)
    assert.equal(await sheets(), 0)
    const raw = await p.evaluate(() => localStorage.getItem('achieve-v3'))
    assert.ok(!raw.includes('งานลับมาก'), 'plaintext leaked')
    const t = (await doc()).tasks.find((x) => x.private)
    assert.ok(t.enc && t.title === '')
  })

  await step('lock hides, unlock reveals', async () => {
    await p.evaluate(() => (location.hash = 'tasks'))
    await p.waitForTimeout(400)
    await p.locator('.task-row:has-text("งานลับมาก")').waitFor()
    await p.evaluate(() => window.__store.getState().lock())
    await p.waitForTimeout(200)
    assert.equal(await p.locator('.task-row:has-text("งานลับมาก")').count(), 0)
    await p.click('.task-row:has-text("Private task") .row-title')
    for (const k of '111111') await p.click(`.pin-pad .key[aria-label="${k}"]`)
    await p.locator('.pin-msg.err').waitFor()
    for (const k of '135790') await p.click(`.pin-pad .key[aria-label="${k}"]`)
    await p.locator('.task-editor').waitFor({ timeout: 5000 })
    assert.equal(await p.inputValue('.te-title textarea'), 'งานลับมาก')
    await p.goBack()
    await p.waitForTimeout(400)
  })

  await step('add expense via keypad, edit, delete + undo', async () => {
    await p.evaluate(() => (location.hash = 'money'))
    await p.waitForTimeout(400)
    await p.click('.tabbar .fab')
    for (const k of ['1', '2', '5', '.', '5']) await p.click(`.keypad .key[aria-label="${k}"]`)
    await p.click('.cat:has-text("Transport")')
    await p.click('.sheet button:has-text("Save expense")')
    await p.waitForTimeout(400)
    let tx = (await doc()).txs.find((x) => x.category === 'เดินทาง')
    assert.equal(tx.amount, 12550)
    await p.click('.tx-row:has-text("Transport")')
    await p.click('.sheet .key[aria-label="Delete"]')
    await p.click('.sheet button:has-text("Save")')
    await p.waitForTimeout(300)
    tx = (await doc()).txs.find((x) => x.id === tx.id)
    assert.equal(tx.amount, 12500)
    await p.click('.tx-row:has-text("Transport")')
    await p.click('button[aria-label="Delete transaction"]')
    await p.waitForTimeout(300)
    assert.ok((await doc()).txs.find((x) => x.id === tx.id).deleted, 'not deleted')
    await p.click('.toast .undo')
    await p.waitForTimeout(1500)
    assert.ok(!(await doc()).txs.find((x) => x.id === tx.id).deleted, 'undo failed')
    const shown = await p.textContent('.mh-amount')
    assert.ok(shown.includes('125'), 'hero shows ' + shown)
  })

  await step('budget + goal deposit', async () => {
    await p.click('button:has-text("Set a monthly budget")')
    for (const k of '5000') await p.click(`.sheet .key[aria-label="${k}"]`)
    await p.click('.sheet-foot button:has-text("Save")')
    await p.waitForTimeout(300)
    assert.equal((await doc()).settings[0].budget, 500000)
    await p.click('button:has-text("New goal")')
    await p.fill('.sheet input.big-input', 'กองทุนฉุกเฉิน')
    await p.fill('.sheet input[inputmode="decimal"]', '10000')
    await p.click('.sheet-foot button:has-text("Save")')
    await p.click('.goal-card')
    await p.fill('.ge-input input', '750')
    await p.click('.ge-row .btn')
    await p.waitForTimeout(300)
    assert.equal((await doc()).goalEntries[0].amount, 75000)
    assert.ok((await p.textContent('.gh-pct')).includes('8'))
    await p.goBack()
  })

  await step('habit check-in + new habit', async () => {
    await p.evaluate(() => (location.hash = 'habits'))
    await p.waitForTimeout(400)
    await p.click('.habit-grid .habit-orb >> nth=1')
    await p.waitForTimeout(300)
    assert.ok((await doc()).habitLogs.some((l) => l.habitId === 'habit-think-before-buy' && !l.deleted))
    await p.click('button[aria-label="New habit"]')
    await p.fill('.sheet input.big-input', 'ออกกำลังกาย')
    await p.click('.segmented button:has-text("Some days")')
    await p.click('.sheet-foot .btn-primary')
    await p.waitForTimeout(300)
    const h = (await doc()).habits.find((x) => x.title === 'ออกกำลังกาย')
    assert.deepEqual(h.days, [1, 2, 3, 4, 5])
  })

  await step('event conflict warning on class time', async () => {
    await p.evaluate(() => (location.hash = 'plan'))
    await p.waitForTimeout(400)
    await p.click('button[aria-label="New event"]')
    await p.fill('.sheet input.big-input', 'ติวเพื่อน')
    await p.fill('.sheet input[type="date"]', '2026-09-28')
    await p.fill('.sheet input[type="time"] >> nth=0', '10:30')
    await p.fill('.sheet input[type="time"] >> nth=1', '11:30')
    await p.locator('.note.warn:has-text("Mobile")').waitFor()
    await p.click('.sheet button:has-text("Save anyway")')
    await p.waitForTimeout(300)
    assert.ok((await doc()).events.some((e) => e.title === 'ติวเพื่อน' && e.date === '2026-09-28'))
  })

  await step('schedule task into free slot', async () => {
    await p.evaluate(() => (location.hash = 'tasks'))
    await p.waitForTimeout(300)
    await p.click('.task-row:has-text("ทดสอบงาน A") .row-title')
    await p.click('.sheet button:has-text("Block free time")')
    await p.click('.slot-pick >> nth=0')
    await p.waitForTimeout(300)
    const d = await doc()
    const t = d.tasks.find((x) => x.title === 'ทดสอบงาน A')
    assert.ok(d.events.some((e) => e.taskId === t.id))
    await p.goBack()
  })

  await step('data survives reload', async () => {
    await p.reload()
    await p.locator('h1').first().waitFor()
    await p.evaluate(() => (location.hash = 'tasks'))
    await p.locator('.task-row:has-text("ทดสอบงาน A")').waitFor()
  })

  await step('no horizontal overflow on any tab', async () => {
    for (const t of ['today', 'tasks', 'plan', 'habits', 'money']) {
      await p.evaluate((x) => (location.hash = x), t)
      await p.waitForTimeout(350)
      const sw = await p.evaluate(() => document.documentElement.scrollWidth)
      assert.ok(sw <= 390, `${t} scrollWidth ${sw}`)
    }
  })

  console.log(errors.length ? 'PAGE ERRORS:\n' + [...new Set(errors)].join('\n') : 'no page errors')
  await b.close()
})()
