const { chromium } = require(process.env.PLAYWRIGHT || 'playwright')
const assert = require('node:assert/strict')
const fs = require('fs')
;(async () => {
  const b = await chromium.launch({ channel: 'chrome' })
  const p = await b.newPage({ viewport: { width: 390, height: 844 }, serviceWorkers: 'block' })
  const errors = []; p.on('pageerror', (e) => errors.push(e.message))
  await p.goto((process.env.URL || 'http://localhost:5173/DairyOptimizer/') + '#tasks')
  await p.waitForFunction(() => window.__store)
  await p.evaluate(() => { const s = window.__store.getState(); for (const t of ['A','B']) s.put('tasks', { id: 't'+t, updatedAt: 0, title: 'งาน '+t, notes: '', checklist: [], due: null, plan: null, subjectId: null, duration: 30, flagged: false, doneAt: null, createdAt: 1, private: false, enc: null }) })
  const drag = async (sel, dx) => {
    const box = await p.locator(sel).boundingBox()
    const y = box.y + box.height / 2, x = box.x + box.width / 2
    await p.mouse.move(x, y); await p.mouse.down()
    for (let i = 1; i <= 12; i++) await p.mouse.move(x + (dx * i) / 12, y + i * 0.3)
    await p.mouse.up(); await p.waitForTimeout(600)
  }
  const task = (id) => p.evaluate((i) => window.__store.getState().doc.tasks.find((t) => t.id === i), id)
  await drag('.task-row:has-text("งาน A")', 170)
  assert.ok((await task('tA')).doneAt, 'swipe right should complete')
  await drag('.task-row:has-text("งาน B")', -170)
  assert.equal((await task('tB')).plan !== null, true, 'swipe left on unplanned task plans it today')
  await drag('.task-row:has-text("งาน B")', -170)
  assert.ok((await task('tB')).deleted, 'second swipe left deletes')
  await p.click('.toast .undo'); await p.waitForTimeout(300)
  assert.ok(!(await task('tB')).deleted)
  console.log('swipe ok')

  // Legacy import through Settings
  const legacy = { version: 2, transactions: [{ id: 'lx1', type: 'expense', amount: 99, date: '2026-09-10', note: 'เก่า', category: 'อาหาร', created: 1 }], tasks: [{ id: 'lt1', done: false, locked: false, title: 'งานจากแอปเดิม', notes: '', due: '2026-10-01', duration: 30, priority: 'normal' }], events: [], savings: [], goal: { name: 'เงินเก็บก้อนแรก', target: 10000 }, budget: 6000, budgetConfigured: false, subjects: [], schedule: [], habits: [], habitLogs: [] }
  const legacyFile = require('path').join(require('os').tmpdir(), 'achieve-legacy.json')
  fs.writeFileSync(legacyFile, JSON.stringify(legacy))
  await p.evaluate(() => (location.hash = 'today'))
  await p.click('button[aria-label="Settings"]')
  const [chooser] = await Promise.all([p.waitForEvent('filechooser'), p.click('button:has-text("Import")')])
  await chooser.setFiles(legacyFile)
  await p.locator('.import-card').waitFor()
  await p.click('.import-card .btn-primary')
  await p.waitForTimeout(500)
  const d = await p.evaluate(() => window.__store.getState().doc)
  assert.ok(d.tasks.some((t) => t.title === 'งานจากแอปเดิม' && t.due === '2026-10-01'))
  assert.ok(d.txs.some((t) => t.id === 'lx1' && t.amount === 9900))
  assert.equal(d.classes.filter((c) => !c.deleted).length, 12)
  console.log('legacy import ok')
  console.log(errors.length ? errors.join('\n') : 'no page errors')
  await b.close()
})()
